### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn.externals.joblib

### ISSUE THREAD

**Issue by satcos** [razhangwei/CAUSE#2]
Scripts throw "ModuleNotFoundError: No module named 'sklearn.externals.joblib'" error

Traceback (most recent call last):
  File "/Users/user1/MyGitRepo/CAUSE/tasks/train.py", line 269, in <module>
    model = get_model(args, n_types)
  File "/Users/user1/MyGitRepo/CAUSE/tasks/train.py", line 61, in get_model
    from tick.hawkes import HawkesExpKern
  File "/Users/user1/opt/miniconda3/envs/Cause/lib/python3.7/site-packages/tick/hawkes/__init__.py", line 3, in <module>
    from .model import (
  File "/Users/user1/opt/miniconda3/envs/Cause/lib/python3.7/site-packages/tick/hawkes/model/__init__.py", line 4, in <module>
    import tick.base_model.build.base_model
  File "/Users/user1/opt/miniconda3/envs/Cause/lib/python3.7/site-packages/tick/base_model/__init__.py", line 5, in <module>
    from .model_labels_features import ModelLabelsFeatures
  File "/Users/user1/opt/miniconda3/envs/Cause/lib/python3.7/site-packages/tick/base_model/model_labels_features.py", line 6, in <module>
    from tick.preprocessing.utils import safe_array
  File "/Users/user1/opt/miniconda3/envs/Cause/lib/python3.7/site-packages/tick/preprocessing/__init__.py", line 4, in <module>
    from .longitudinal_features_product import LongitudinalFeaturesProduct
  File "/Users/user1/opt/miniconda3/envs/Cause/lib/python3.7/site-packages/tick/preprocessing/longitudinal_features_product.py", line 8, in <module>
    from sklearn.externals.joblib import Parallel, delayed
ModuleNotFoundError: No module named 'sklearn.externals.joblib'

**Comment by razhangwei** [comment]
It should be an issue of `tick`, as the `sklearn` does not bundle `joblib` since recent versions. Can you try editing that `ongitudinal_features_product.py` file to `from joblib import Parallel, delayed`?

**Comment by satcos** [comment]
In my local copy I edited the import function from tick library.

This issues is already reported and fixed in tick, waiting for release.
https://github.com/X-DataInitiative/tick/issues/459
